# Generated by Django 3.2 on 2021-06-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_budget', models.FloatField(default=0.0)),
                ('vendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_account.vendor')),
            ],
        ),
    ]
