# Generated by Django 3.2 on 2021-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_account', '0004_auto_20210606_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
